---
- name: running setup
  hosts: all
  become: true
  
  vars_prompt:
    - name: roles_index
      prompt: Enter "1" for role-prerequisites and "2" for list-interfaces 
      private : no

  roles:
  - { "role": "prerequisites", when: roles_index == "1" }
  - { "role": "list-interfaces", when: roles_index == "2"}
